language: node_js
node_js:
    - "stable"

script:
    yarn build

install:
  - npm install react react-scripts react-dom react-router react-router-dom react-bootstrap bootstrap
  - npm install -g firebase-tools


after_success:
    - firebase -deploy --token 1//0fENpYmpLVlZECgYIARAAGA8SNwF-L9Ir0E0sl7AJm0ObahlQuHS50yw7gm-4YmXlPB99IoiM2q5U7-Tu6ECyXz1l_UkRiL8igEI
